### ISSUE TITLE
Multiple tabs of the same file is opened when clicked on the file again from the explorer

### ISSUE THREAD

**Issue by vyshnav-vinod** [billyeatcookies/biscuit#244]
## Bug
> Describe the bug

When i clicked on a file from the explorer twice, it actually opened two tabs of the same file (I hope i am being clear here). And it will continue to open a new tab for that file everytime it is clicked from the explorer. Isnt it suppose to only open once??

### System Information
- OS: Fedora Linux 39
- Python Version: 3.12.2

Aside from that great editor BTW <3

**Comment by vyshnav-vinod** [comment]
Ok so i tried to kinda fix the error myself and i cant seem to get the development environment running. I tried both `pip` and `poetry` but it fails when building `tkextrafont` . Is it only an issue for me or is it common? I tried this with the latest python version and `python 3.10` as well. `Python 3.10` was a mess as it couldnt build `setuptools` for some reason. So i switched back to `3.12` and `tkextrafont` was the main issue.

```bash
  RuntimeError

  Unable to find installation candidates for tkextrafont (0.6.3)

  at ~/.local/share/pipx/venvs/poetry/lib64/python3.12/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│ 
       71│             links.append(link)
       72│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│ 

Cannot install tkextrafont.
```

This is what i got

**Comment by billyeatcookies** [comment]
@vyshnav-vinod the `tkextrafont` package is actually troublesome and like 30% of the bugs listed are caused by the package alone. I expect we can go independent of the lib in future. True that it requires prerequisites to be installed before pip install on linux distros, I should've mentioned it explicitly in docs. Sorry for the trouble caused.

Now getting back to the issue, yes the behavior is not expected from user perspective, so it needs to be fixed.
Now if you are interested in contributing, the issue can be solved by doing a simple is_open check while opening a new editor 

- [`is_open`](https://github.com/billyeatcookies/biscuit/blob/main/biscuit/core/layout/base/content/editors/__init__.py#L62)
- [`open_editor`](https://github.com/billyeatcookies/biscuit/blob/main/biscuit/core/layout/base/content/editors/__init__.py#L103)

**Comment by vyshnav-vinod** [comment]
Yea the `tkextrafont` library seems to be really troublesome. It would be nice to add the prerequisities for `tkextrafont` as a FAQ or something? If someone comes looking for it. 
And for the issue, yea i checked `open_editor` and noticed it also has an `exists` argument. Does `exists` and `is_open` mean the same thing here?

**Comment by billyeatcookies** [comment]
@vyshnav-vinod I'll add the prerequisites to CONTRIBUTING(.md) guidelines. 

The `exists` argument kind of popped up as a necessity when non existing editors were added to Biscuit (eg. The new-file command will create a non existing editor that is not pointing to an existing file; another example would be the game editors / settings editor).

So, if you call `open_editor` for an existing path and want biscuit to load the file's contents (which you should), you must give `exists=True`. The argument exists solely for the purpose of assisting in the opening of non-existent editors :)

`is_open` on the other hand is not related to `exists`, this method will check if the an editor instance is existing in the already opened editors list.
